version: '3.4'

services:

  sql-server:
    container_name: sql-edge
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "Test@1@2"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"

  sportsstore.webapp:
    image: ${DOCKER_REGISTRY-}sportsstore
    build:
      context: .
      dockerfile: src/SportsStore.WebApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "7443:443"
    volumes:
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
    depends_on:
      - sql-server
